In [2]:
import pandas as pd

In [17]:
df = pd.read_csv('../notebooks/data/big_data.csv')

In [18]:
df.head(100)

                                            headlines  outcome
0   Medical director at PHE Dr Yvonne Doyle says h...        0
1   Fourteen new cases of #COVID19 have been repor...        0
2   Acc to @MoHFW_INDIA as per the current evidenc...        0
3   We also found that death data made it more dif...        0
4   .@WHO reconsiders the airborne nature of #COVI...        0
..                                                ...      ...
95  #ERSCongress will dissect the debate of the va...        0
96  @WeVotedToLeave @PathogenScribe In India they ...        1
97  The latest updates from the Ministry of Health...        0
98  This week we’ll reach 20 million registered ca...        0
99  #CoronaCheck: Are Victoria's recent #COVID19 o...        1

[100 rows x 2 columns]

In [8]:
len(df['outcome'])

19573

In [11]:
df.value_counts('outcome')

outcome
1    10854
0     8719
Name: count, dtype: int64

In [12]:
df.value_counts

<bound method DataFrame.value_counts of                                                headlines  outcome
0      Medical director at PHE Dr Yvonne Doyle says h...        0
1      Fourteen new cases of #COVID19 have been repor...        0
2      Acc to @MoHFW_INDIA as per the current evidenc...        0
3      We also found that death data made it more dif...        0
4      .@WHO reconsiders the airborne nature of #COVI...        0
...                                                  ...      ...
19568  Multiple Facebook posts claim that “Aussies wi...        1
19569  We are delighted that 78 high- and upper-middl...        0
19570  Health equity is when everyone has the opportu...        0
19571  "States like New York, Illinois and California...        1
19572  ???Clearly, the Obama administration did not l...        1

[19573 rows x 2 columns]>

In [ ]:
19573
0.44

In [13]:
df = pd.read_csv('../data/data.csv')

In [14]:
df.value_counts('outcome')

outcome
0    9727
1     474
Name: count, dtype: int64

In [15]:
df.value_counts

<bound method DataFrame.value_counts of                                                headlines  outcome
0      A post claims compulsory vacination violates t...        0
1      A photo claims that this person is a doctor wh...        0
2      Post about a video claims that it is a protest...        0
3      All deaths by respiratory failure and pneumoni...        0
4      The dean of the College of Biologists of Euska...        0
...                                                  ...      ...
10196  A Chinese market caused the new coronavirus (v...        0
10197  The peak of the new coronavirus will happen in...        0
10198  Stores and supermarkets in Veracruz (Mexico) w...        0
10199  A chain message circulated on Tuesday, Jan. 14...        0
10200  Photo shows Muslims in Tamil Nadu state of Ind...        0

[10201 rows x 2 columns]>

In [24]:
df = pd.read_csv('file_predictions_single.csv')

In [25]:
df.head()

,group_id,id,text,prediction,accuracy,model_selected,date
0,0,0,CDC has given more than $200M to address #COVI...,True,99.99,sequential,2024-01-17 20:24:58.416812
1,0,1,#IndiaFightsCorona TEST TRACK TREAT- effective...,True,97.63,sequential,2024-01-17 20:25:43.844285
2,0,2,"Ireland's entire cabinet will ""restrict their ...",Fake,70.45,sequential,2024-01-17 20:25:47.824122
3,0,3,The Chairman of the Republican Party of Texas ...,True,98.29,sequential,2024-01-17 20:25:47.824218
4,0,4,Iranians have published a report saying that c...,Fake,99.93,sequential,2024-01-17 20:25:47.824272

In [29]:
filtered_df = df[df['group_id'] == "1"]

In [30]:
filtered_df.head(100)

Empty DataFrame
Columns: [group_id, id, text, prediction, accuracy, model_selected, date]
Index: []

In [56]:
# 1, 'text1', '1', '0.9', 'model1', '2019-01-01'
# 2, 'text2', '0', '0.8', 'model1', '2019-01-01'
# 3, 'text3', '1', '0.7', 'model1', '2019-01-01'
# 4, 'text4', '0', '0.6', 'model1', '2019-01-01'